## remotes::install_github("JohnCoene/typed")
## remotes::install_github("ayayron/shinydnd")
library(typed)
library(shiny)
library(shinyjs)
library(shinyWidgets)
library(shinyRadioMatrix)
library(ggplot2)
library(ggsn)
library(shinyDND)
library(stringr)


source("scripts/pumpkin.r")
source("scripts/chickens.r")
source("scripts/tomgro.r")
